### ISSUE TITLE
i cant run this program

### ISSUE THREAD

**Issue by y4f** [Umoxfo/vscode-w3cvalidation#2]
[Info  - 5:29:48 PM] Connection to server got closed. Server will restart.
c:\Users\yoshiki\.vscode\extensions\umoxfo.vscode-w3cvalidation-2.1.1\server\out\server.js:7
import { createConnection, ProposedFeatures, TextDocuments, DiagnosticSeverity } from "vscode-language-server";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Server.<anonymous> (C:\Users\yoshiki\.vscode\extensions\umoxfo.vscode-w3cvalidation-2.1.1\client\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
[Error - 5:29:48 PM] Connection to server got closed. Server will not be restarted.

**Comment by y4f** [comment]
solve
