### ISSUE TITLE
Can't get it Work on OS X

### ISSUE THREAD

**Issue by Marvv90** [Umoxfo/vscode-w3cvalidation#29]
Hi, 

i have installed W3C Validation V. 2.8.0 from the Extension Market inside Visual Studio Code on a OS X Big Sur v.11.2.1 and can't do anything right that it works. 

Set Java Path with different Paths but nothing work.

I need your Help.

The only Message that i received: 

undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/XXXXX/.vscode/extensions/umoxfo.vscode-w3cvalidation-2.8.0/server/out/server.js:1:100472)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[Info  - 9:00:19 PM] Connection to server got closed. Server will restart.

**Comment by WaReZoR-UA** [comment]
Same!

**Comment by Carl20cent** [comment]
Same ! (MacOS 12.6 - VSCode 1.73.1 - W3C Validation v2.9.1)
But, in my case, the extension worked before !
I've tried to uninstall & reinstall the extension, but same error...
